# Generated by Django 5.2.6 on 2025-09-23 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('quiet', '安靜空間'), ('charging', '可充電'), ('general', '一般空間'), ('room', '房間'), ('exercise', '運動空間'), ('eat', '飲食空間')], max_length=20),
        ),
    ]
