# Generated by Django 5.2.6 on 2025-09-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('estimated_time', models.IntegerField(blank=True, null=True)),
                ('environment', models.CharField(blank=True, choices=[('電腦', '電腦'), ('紙筆', '紙筆'), ('平板', '平板'), ('安靜空間', '安靜空間')], max_length=20)),
                ('priority', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
