# Generated by Django 5.2.6 on 2025-10-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('estimated_time', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=3)),
                ('environment', models.CharField(blank=True, choices=[('laptop', '需要電腦'), ('writing', '需要紙筆'), ('tablet', '需要平板'), ('quiet', '安靜環境'), ('group', '團隊合作'), ('exercise', '運動空間'), ('eat', '飲食/邊吃邊做'), ('laundry', '洗衣相關'), ('relax', '休閒/放鬆'), ('other', '其他')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
